
  create table "public"."children" (
    "id" integer generated by default as identity not null,
    "name" text not null
      );


alter table "public"."children" enable row level security;


  create table "public"."ethnicities" (
    "id" integer generated by default as identity not null,
    "name" text not null
      );


alter table "public"."ethnicities" enable row level security;


  create table "public"."family_plans" (
    "id" integer generated by default as identity not null,
    "name" text not null
      );


alter table "public"."family_plans" enable row level security;


  create table "public"."interactions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "updated_by" uuid not null,
    "actor_id" uuid not null,
    "target_id" uuid not null,
    "status_id" bigint not null,
    "answer_id" uuid,
    "photo_id" uuid
      );


alter table "public"."interactions" enable row level security;


  create table "public"."interaction_status" (
    "id" bigint generated by default as identity not null,
    "status" text not null
      );


alter table "public"."interaction_status" enable row level security;


  create table "public"."pets" (
    "id" integer generated by default as identity not null,
    "name" text not null
      );


alter table "public"."pets" enable row level security;


  create table "public"."profile_answers" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp without time zone not null default now(),
    "profile_id" uuid not null,
    "prompt_id" integer not null,
    "answer_text" text not null,
    "answer_order" smallint not null,
    "is_active" boolean not null
      );


alter table "public"."profile_answers" enable row level security;


  create table "public"."profile_ethnicities" (
    "profile_id" uuid not null,
    "ethnicity_id" integer not null
      );


alter table "public"."profile_ethnicities" enable row level security;


  create table "public"."profile_ethnicity_preferences" (
    "profile_id" uuid not null,
    "ethnicity_id" integer not null
      );


alter table "public"."profile_ethnicity_preferences" enable row level security;


  create table "public"."profile_pets" (
    "profile_id" uuid not null,
    "pet_id" integer not null
      );


alter table "public"."profile_pets" enable row level security;


  create table "public"."profile_photos" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "profile_id" uuid not null,
    "photo_url" text not null,
    "photo_order" smallint not null,
    "is_active" boolean not null
      );


alter table "public"."profile_photos" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "first_name" text not null,
    "dob" date not null,
    "height_cm" integer,
    "neighborhood" text,
    "latitude" double precision,
    "longitude" double precision,
    "children_id" integer,
    "family_plan_id" integer,
    "max_distance_km" integer default 160,
    "min_age" integer default 18,
    "max_age" integer default 100,
    "phone" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."prompts" (
    "id" integer generated by default as identity not null,
    "question" text not null
      );


alter table "public"."prompts" enable row level security;

CREATE UNIQUE INDEX children_pkey ON public.children USING btree (id);

CREATE UNIQUE INDEX ethnicities_pkey ON public.ethnicities USING btree (id);

CREATE UNIQUE INDEX family_plans_pkey ON public.family_plans USING btree (id);

CREATE UNIQUE INDEX interactions_pkey ON public.interactions USING btree (id);

CREATE UNIQUE INDEX interaction_status_pkey ON public.interaction_status USING btree (id);

CREATE UNIQUE INDEX pets_pkey ON public.pets USING btree (id);

CREATE UNIQUE INDEX profile_answers_pkey ON public.profile_answers USING btree (id);

CREATE UNIQUE INDEX profile_ethnicities_pkey ON public.profile_ethnicities USING btree (profile_id, ethnicity_id);

CREATE UNIQUE INDEX profile_ethnicity_preferences_pkey ON public.profile_ethnicity_preferences USING btree (profile_id, ethnicity_id);

CREATE UNIQUE INDEX profile_pets_pkey ON public.profile_pets USING btree (profile_id, pet_id);

CREATE UNIQUE INDEX profile_photos_pkey ON public.profile_photos USING btree (id);

CREATE UNIQUE INDEX profiles_phone_key ON public.profiles USING btree (phone);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX prompts_pkey ON public.prompts USING btree (id);

alter table "public"."children" add constraint "children_pkey" PRIMARY KEY using index "children_pkey";

alter table "public"."ethnicities" add constraint "ethnicities_pkey" PRIMARY KEY using index "ethnicities_pkey";

alter table "public"."family_plans" add constraint "family_plans_pkey" PRIMARY KEY using index "family_plans_pkey";

alter table "public"."interactions" add constraint "interactions_pkey" PRIMARY KEY using index "interactions_pkey";

alter table "public"."interaction_status" add constraint "interaction_status_pkey" PRIMARY KEY using index "interaction_status_pkey";

alter table "public"."pets" add constraint "pets_pkey" PRIMARY KEY using index "pets_pkey";

alter table "public"."profile_answers" add constraint "profile_answers_pkey" PRIMARY KEY using index "profile_answers_pkey";

alter table "public"."profile_ethnicities" add constraint "profile_ethnicities_pkey" PRIMARY KEY using index "profile_ethnicities_pkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicity_preferences_pkey" PRIMARY KEY using index "profile_ethnicity_preferences_pkey";

alter table "public"."profile_pets" add constraint "profile_pets_pkey" PRIMARY KEY using index "profile_pets_pkey";

alter table "public"."profile_photos" add constraint "profile_photos_pkey" PRIMARY KEY using index "profile_photos_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."prompts" add constraint "prompts_pkey" PRIMARY KEY using index "prompts_pkey";

alter table "public"."interactions" add constraint "interactions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES public.profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_actor_id_fkey";

alter table "public"."interactions" add constraint "interactions_answer_id_fkey" FOREIGN KEY (answer_id) REFERENCES public.profile_answers(id) not valid;

alter table "public"."interactions" validate constraint "interactions_answer_id_fkey";

alter table "public"."interactions" add constraint "interactions_photo_id_fkey" FOREIGN KEY (photo_id) REFERENCES public.profile_photos(id) not valid;

alter table "public"."interactions" validate constraint "interactions_photo_id_fkey";

alter table "public"."interactions" add constraint "interactions_status_id_fkey" FOREIGN KEY (status_id) REFERENCES public.interaction_status(id) not valid;

alter table "public"."interactions" validate constraint "interactions_status_id_fkey";

alter table "public"."interactions" add constraint "interactions_target_id_fkey" FOREIGN KEY (target_id) REFERENCES public.profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_target_id_fkey";

alter table "public"."interactions" add constraint "interactions_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES public.profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_updated_by_fkey";

alter table "public"."profile_answers" add constraint "profile_answers_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_answers" validate constraint "profile_answers_profile_id_fkey";

alter table "public"."profile_answers" add constraint "profile_answers_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES public.prompts(id) not valid;

alter table "public"."profile_answers" validate constraint "profile_answers_prompt_id_fkey";

alter table "public"."profile_ethnicities" add constraint "profile_ethnicities_ethnicity_id_fkey" FOREIGN KEY (ethnicity_id) REFERENCES public.ethnicities(id) not valid;

alter table "public"."profile_ethnicities" validate constraint "profile_ethnicities_ethnicity_id_fkey";

alter table "public"."profile_ethnicities" add constraint "profile_ethnicities_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_ethnicities" validate constraint "profile_ethnicities_profile_id_fkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicity_preferences_ethnicity_id_fkey" FOREIGN KEY (ethnicity_id) REFERENCES public.ethnicities(id) not valid;

alter table "public"."profile_ethnicity_preferences" validate constraint "profile_ethnicity_preferences_ethnicity_id_fkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicity_preferences_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_ethnicity_preferences" validate constraint "profile_ethnicity_preferences_profile_id_fkey";

alter table "public"."profile_pets" add constraint "profile_pets_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES public.pets(id) not valid;

alter table "public"."profile_pets" validate constraint "profile_pets_pet_id_fkey";

alter table "public"."profile_pets" add constraint "profile_pets_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_pets" validate constraint "profile_pets_profile_id_fkey";

alter table "public"."profile_photos" add constraint "profile_photos_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_photos" validate constraint "profile_photos_profile_id_fkey";

alter table "public"."profiles" add constraint "profiles_children_id_fkey" FOREIGN KEY (children_id) REFERENCES public.children(id) not valid;

alter table "public"."profiles" validate constraint "profiles_children_id_fkey";

alter table "public"."profiles" add constraint "profiles_family_plan_id_fkey" FOREIGN KEY (family_plan_id) REFERENCES public.family_plans(id) not valid;

alter table "public"."profiles" validate constraint "profiles_family_plan_id_fkey";

alter table "public"."profiles" add constraint "profiles_phone_key" UNIQUE using index "profiles_phone_key";

grant delete on table "public"."children" to "anon";

grant insert on table "public"."children" to "anon";

grant references on table "public"."children" to "anon";

grant select on table "public"."children" to "anon";

grant trigger on table "public"."children" to "anon";

grant truncate on table "public"."children" to "anon";

grant update on table "public"."children" to "anon";

grant delete on table "public"."children" to "authenticated";

grant insert on table "public"."children" to "authenticated";

grant references on table "public"."children" to "authenticated";

grant select on table "public"."children" to "authenticated";

grant trigger on table "public"."children" to "authenticated";

grant truncate on table "public"."children" to "authenticated";

grant update on table "public"."children" to "authenticated";

grant delete on table "public"."children" to "postgres";

grant insert on table "public"."children" to "postgres";

grant references on table "public"."children" to "postgres";

grant select on table "public"."children" to "postgres";

grant trigger on table "public"."children" to "postgres";

grant truncate on table "public"."children" to "postgres";

grant update on table "public"."children" to "postgres";

grant delete on table "public"."children" to "service_role";

grant insert on table "public"."children" to "service_role";

grant references on table "public"."children" to "service_role";

grant select on table "public"."children" to "service_role";

grant trigger on table "public"."children" to "service_role";

grant truncate on table "public"."children" to "service_role";

grant update on table "public"."children" to "service_role";

grant delete on table "public"."ethnicities" to "anon";

grant insert on table "public"."ethnicities" to "anon";

grant references on table "public"."ethnicities" to "anon";

grant select on table "public"."ethnicities" to "anon";

grant trigger on table "public"."ethnicities" to "anon";

grant truncate on table "public"."ethnicities" to "anon";

grant update on table "public"."ethnicities" to "anon";

grant delete on table "public"."ethnicities" to "authenticated";

grant insert on table "public"."ethnicities" to "authenticated";

grant references on table "public"."ethnicities" to "authenticated";

grant select on table "public"."ethnicities" to "authenticated";

grant trigger on table "public"."ethnicities" to "authenticated";

grant truncate on table "public"."ethnicities" to "authenticated";

grant update on table "public"."ethnicities" to "authenticated";

grant delete on table "public"."ethnicities" to "postgres";

grant insert on table "public"."ethnicities" to "postgres";

grant references on table "public"."ethnicities" to "postgres";

grant select on table "public"."ethnicities" to "postgres";

grant trigger on table "public"."ethnicities" to "postgres";

grant truncate on table "public"."ethnicities" to "postgres";

grant update on table "public"."ethnicities" to "postgres";

grant delete on table "public"."ethnicities" to "service_role";

grant insert on table "public"."ethnicities" to "service_role";

grant references on table "public"."ethnicities" to "service_role";

grant select on table "public"."ethnicities" to "service_role";

grant trigger on table "public"."ethnicities" to "service_role";

grant truncate on table "public"."ethnicities" to "service_role";

grant update on table "public"."ethnicities" to "service_role";

grant delete on table "public"."family_plans" to "anon";

grant insert on table "public"."family_plans" to "anon";

grant references on table "public"."family_plans" to "anon";

grant select on table "public"."family_plans" to "anon";

grant trigger on table "public"."family_plans" to "anon";

grant truncate on table "public"."family_plans" to "anon";

grant update on table "public"."family_plans" to "anon";

grant delete on table "public"."family_plans" to "authenticated";

grant insert on table "public"."family_plans" to "authenticated";

grant references on table "public"."family_plans" to "authenticated";

grant select on table "public"."family_plans" to "authenticated";

grant trigger on table "public"."family_plans" to "authenticated";

grant truncate on table "public"."family_plans" to "authenticated";

grant update on table "public"."family_plans" to "authenticated";

grant delete on table "public"."family_plans" to "postgres";

grant insert on table "public"."family_plans" to "postgres";

grant references on table "public"."family_plans" to "postgres";

grant select on table "public"."family_plans" to "postgres";

grant trigger on table "public"."family_plans" to "postgres";

grant truncate on table "public"."family_plans" to "postgres";

grant update on table "public"."family_plans" to "postgres";

grant delete on table "public"."family_plans" to "service_role";

grant insert on table "public"."family_plans" to "service_role";

grant references on table "public"."family_plans" to "service_role";

grant select on table "public"."family_plans" to "service_role";

grant trigger on table "public"."family_plans" to "service_role";

grant truncate on table "public"."family_plans" to "service_role";

grant update on table "public"."family_plans" to "service_role";

grant delete on table "public"."interactions" to "anon";

grant insert on table "public"."interactions" to "anon";

grant references on table "public"."interactions" to "anon";

grant select on table "public"."interactions" to "anon";

grant trigger on table "public"."interactions" to "anon";

grant truncate on table "public"."interactions" to "anon";

grant update on table "public"."interactions" to "anon";

grant delete on table "public"."interactions" to "authenticated";

grant insert on table "public"."interactions" to "authenticated";

grant references on table "public"."interactions" to "authenticated";

grant select on table "public"."interactions" to "authenticated";

grant trigger on table "public"."interactions" to "authenticated";

grant truncate on table "public"."interactions" to "authenticated";

grant update on table "public"."interactions" to "authenticated";

grant delete on table "public"."interactions" to "postgres";

grant insert on table "public"."interactions" to "postgres";

grant references on table "public"."interactions" to "postgres";

grant select on table "public"."interactions" to "postgres";

grant trigger on table "public"."interactions" to "postgres";

grant truncate on table "public"."interactions" to "postgres";

grant update on table "public"."interactions" to "postgres";

grant delete on table "public"."interactions" to "service_role";

grant insert on table "public"."interactions" to "service_role";

grant references on table "public"."interactions" to "service_role";

grant select on table "public"."interactions" to "service_role";

grant trigger on table "public"."interactions" to "service_role";

grant truncate on table "public"."interactions" to "service_role";

grant update on table "public"."interactions" to "service_role";

grant delete on table "public"."interaction_status" to "anon";

grant insert on table "public"."interaction_status" to "anon";

grant references on table "public"."interaction_status" to "anon";

grant select on table "public"."interaction_status" to "anon";

grant trigger on table "public"."interaction_status" to "anon";

grant truncate on table "public"."interaction_status" to "anon";

grant update on table "public"."interaction_status" to "anon";

grant delete on table "public"."interaction_status" to "authenticated";

grant insert on table "public"."interaction_status" to "authenticated";

grant references on table "public"."interaction_status" to "authenticated";

grant select on table "public"."interaction_status" to "authenticated";

grant trigger on table "public"."interaction_status" to "authenticated";

grant truncate on table "public"."interaction_status" to "authenticated";

grant update on table "public"."interaction_status" to "authenticated";

grant delete on table "public"."interaction_status" to "postgres";

grant insert on table "public"."interaction_status" to "postgres";

grant references on table "public"."interaction_status" to "postgres";

grant select on table "public"."interaction_status" to "postgres";

grant trigger on table "public"."interaction_status" to "postgres";

grant truncate on table "public"."interaction_status" to "postgres";

grant update on table "public"."interaction_status" to "postgres";

grant delete on table "public"."interaction_status" to "service_role";

grant insert on table "public"."interaction_status" to "service_role";

grant references on table "public"."interaction_status" to "service_role";

grant select on table "public"."interaction_status" to "service_role";

grant trigger on table "public"."interaction_status" to "service_role";

grant truncate on table "public"."interaction_status" to "service_role";

grant update on table "public"."interaction_status" to "service_role";

grant delete on table "public"."pets" to "anon";

grant insert on table "public"."pets" to "anon";

grant references on table "public"."pets" to "anon";

grant select on table "public"."pets" to "anon";

grant trigger on table "public"."pets" to "anon";

grant truncate on table "public"."pets" to "anon";

grant update on table "public"."pets" to "anon";

grant delete on table "public"."pets" to "authenticated";

grant insert on table "public"."pets" to "authenticated";

grant references on table "public"."pets" to "authenticated";

grant select on table "public"."pets" to "authenticated";

grant trigger on table "public"."pets" to "authenticated";

grant truncate on table "public"."pets" to "authenticated";

grant update on table "public"."pets" to "authenticated";

grant delete on table "public"."pets" to "postgres";

grant insert on table "public"."pets" to "postgres";

grant references on table "public"."pets" to "postgres";

grant select on table "public"."pets" to "postgres";

grant trigger on table "public"."pets" to "postgres";

grant truncate on table "public"."pets" to "postgres";

grant update on table "public"."pets" to "postgres";

grant delete on table "public"."pets" to "service_role";

grant insert on table "public"."pets" to "service_role";

grant references on table "public"."pets" to "service_role";

grant select on table "public"."pets" to "service_role";

grant trigger on table "public"."pets" to "service_role";

grant truncate on table "public"."pets" to "service_role";

grant update on table "public"."pets" to "service_role";

grant delete on table "public"."profile_answers" to "anon";

grant insert on table "public"."profile_answers" to "anon";

grant references on table "public"."profile_answers" to "anon";

grant select on table "public"."profile_answers" to "anon";

grant trigger on table "public"."profile_answers" to "anon";

grant truncate on table "public"."profile_answers" to "anon";

grant update on table "public"."profile_answers" to "anon";

grant delete on table "public"."profile_answers" to "authenticated";

grant insert on table "public"."profile_answers" to "authenticated";

grant references on table "public"."profile_answers" to "authenticated";

grant select on table "public"."profile_answers" to "authenticated";

grant trigger on table "public"."profile_answers" to "authenticated";

grant truncate on table "public"."profile_answers" to "authenticated";

grant update on table "public"."profile_answers" to "authenticated";

grant delete on table "public"."profile_answers" to "postgres";

grant insert on table "public"."profile_answers" to "postgres";

grant references on table "public"."profile_answers" to "postgres";

grant select on table "public"."profile_answers" to "postgres";

grant trigger on table "public"."profile_answers" to "postgres";

grant truncate on table "public"."profile_answers" to "postgres";

grant update on table "public"."profile_answers" to "postgres";

grant delete on table "public"."profile_answers" to "service_role";

grant insert on table "public"."profile_answers" to "service_role";

grant references on table "public"."profile_answers" to "service_role";

grant select on table "public"."profile_answers" to "service_role";

grant trigger on table "public"."profile_answers" to "service_role";

grant truncate on table "public"."profile_answers" to "service_role";

grant update on table "public"."profile_answers" to "service_role";

grant delete on table "public"."profile_ethnicities" to "anon";

grant insert on table "public"."profile_ethnicities" to "anon";

grant references on table "public"."profile_ethnicities" to "anon";

grant select on table "public"."profile_ethnicities" to "anon";

grant trigger on table "public"."profile_ethnicities" to "anon";

grant truncate on table "public"."profile_ethnicities" to "anon";

grant update on table "public"."profile_ethnicities" to "anon";

grant delete on table "public"."profile_ethnicities" to "authenticated";

grant insert on table "public"."profile_ethnicities" to "authenticated";

grant references on table "public"."profile_ethnicities" to "authenticated";

grant select on table "public"."profile_ethnicities" to "authenticated";

grant trigger on table "public"."profile_ethnicities" to "authenticated";

grant truncate on table "public"."profile_ethnicities" to "authenticated";

grant update on table "public"."profile_ethnicities" to "authenticated";

grant delete on table "public"."profile_ethnicities" to "postgres";

grant insert on table "public"."profile_ethnicities" to "postgres";

grant references on table "public"."profile_ethnicities" to "postgres";

grant select on table "public"."profile_ethnicities" to "postgres";

grant trigger on table "public"."profile_ethnicities" to "postgres";

grant truncate on table "public"."profile_ethnicities" to "postgres";

grant update on table "public"."profile_ethnicities" to "postgres";

grant delete on table "public"."profile_ethnicities" to "service_role";

grant insert on table "public"."profile_ethnicities" to "service_role";

grant references on table "public"."profile_ethnicities" to "service_role";

grant select on table "public"."profile_ethnicities" to "service_role";

grant trigger on table "public"."profile_ethnicities" to "service_role";

grant truncate on table "public"."profile_ethnicities" to "service_role";

grant update on table "public"."profile_ethnicities" to "service_role";

grant delete on table "public"."profile_ethnicity_preferences" to "anon";

grant insert on table "public"."profile_ethnicity_preferences" to "anon";

grant references on table "public"."profile_ethnicity_preferences" to "anon";

grant select on table "public"."profile_ethnicity_preferences" to "anon";

grant trigger on table "public"."profile_ethnicity_preferences" to "anon";

grant truncate on table "public"."profile_ethnicity_preferences" to "anon";

grant update on table "public"."profile_ethnicity_preferences" to "anon";

grant delete on table "public"."profile_ethnicity_preferences" to "authenticated";

grant insert on table "public"."profile_ethnicity_preferences" to "authenticated";

grant references on table "public"."profile_ethnicity_preferences" to "authenticated";

grant select on table "public"."profile_ethnicity_preferences" to "authenticated";

grant trigger on table "public"."profile_ethnicity_preferences" to "authenticated";

grant truncate on table "public"."profile_ethnicity_preferences" to "authenticated";

grant update on table "public"."profile_ethnicity_preferences" to "authenticated";

grant delete on table "public"."profile_ethnicity_preferences" to "postgres";

grant insert on table "public"."profile_ethnicity_preferences" to "postgres";

grant references on table "public"."profile_ethnicity_preferences" to "postgres";

grant select on table "public"."profile_ethnicity_preferences" to "postgres";

grant trigger on table "public"."profile_ethnicity_preferences" to "postgres";

grant truncate on table "public"."profile_ethnicity_preferences" to "postgres";

grant update on table "public"."profile_ethnicity_preferences" to "postgres";

grant delete on table "public"."profile_ethnicity_preferences" to "service_role";

grant insert on table "public"."profile_ethnicity_preferences" to "service_role";

grant references on table "public"."profile_ethnicity_preferences" to "service_role";

grant select on table "public"."profile_ethnicity_preferences" to "service_role";

grant trigger on table "public"."profile_ethnicity_preferences" to "service_role";

grant truncate on table "public"."profile_ethnicity_preferences" to "service_role";

grant update on table "public"."profile_ethnicity_preferences" to "service_role";

grant delete on table "public"."profile_pets" to "anon";

grant insert on table "public"."profile_pets" to "anon";

grant references on table "public"."profile_pets" to "anon";

grant select on table "public"."profile_pets" to "anon";

grant trigger on table "public"."profile_pets" to "anon";

grant truncate on table "public"."profile_pets" to "anon";

grant update on table "public"."profile_pets" to "anon";

grant delete on table "public"."profile_pets" to "authenticated";

grant insert on table "public"."profile_pets" to "authenticated";

grant references on table "public"."profile_pets" to "authenticated";

grant select on table "public"."profile_pets" to "authenticated";

grant trigger on table "public"."profile_pets" to "authenticated";

grant truncate on table "public"."profile_pets" to "authenticated";

grant update on table "public"."profile_pets" to "authenticated";

grant delete on table "public"."profile_pets" to "postgres";

grant insert on table "public"."profile_pets" to "postgres";

grant references on table "public"."profile_pets" to "postgres";

grant select on table "public"."profile_pets" to "postgres";

grant trigger on table "public"."profile_pets" to "postgres";

grant truncate on table "public"."profile_pets" to "postgres";

grant update on table "public"."profile_pets" to "postgres";

grant delete on table "public"."profile_pets" to "service_role";

grant insert on table "public"."profile_pets" to "service_role";

grant references on table "public"."profile_pets" to "service_role";

grant select on table "public"."profile_pets" to "service_role";

grant trigger on table "public"."profile_pets" to "service_role";

grant truncate on table "public"."profile_pets" to "service_role";

grant update on table "public"."profile_pets" to "service_role";

grant delete on table "public"."profile_photos" to "anon";

grant insert on table "public"."profile_photos" to "anon";

grant references on table "public"."profile_photos" to "anon";

grant select on table "public"."profile_photos" to "anon";

grant trigger on table "public"."profile_photos" to "anon";

grant truncate on table "public"."profile_photos" to "anon";

grant update on table "public"."profile_photos" to "anon";

grant delete on table "public"."profile_photos" to "authenticated";

grant insert on table "public"."profile_photos" to "authenticated";

grant references on table "public"."profile_photos" to "authenticated";

grant select on table "public"."profile_photos" to "authenticated";

grant trigger on table "public"."profile_photos" to "authenticated";

grant truncate on table "public"."profile_photos" to "authenticated";

grant update on table "public"."profile_photos" to "authenticated";

grant delete on table "public"."profile_photos" to "postgres";

grant insert on table "public"."profile_photos" to "postgres";

grant references on table "public"."profile_photos" to "postgres";

grant select on table "public"."profile_photos" to "postgres";

grant trigger on table "public"."profile_photos" to "postgres";

grant truncate on table "public"."profile_photos" to "postgres";

grant update on table "public"."profile_photos" to "postgres";

grant delete on table "public"."profile_photos" to "service_role";

grant insert on table "public"."profile_photos" to "service_role";

grant references on table "public"."profile_photos" to "service_role";

grant select on table "public"."profile_photos" to "service_role";

grant trigger on table "public"."profile_photos" to "service_role";

grant truncate on table "public"."profile_photos" to "service_role";

grant update on table "public"."profile_photos" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."prompts" to "anon";

grant insert on table "public"."prompts" to "anon";

grant references on table "public"."prompts" to "anon";

grant select on table "public"."prompts" to "anon";

grant trigger on table "public"."prompts" to "anon";

grant truncate on table "public"."prompts" to "anon";

grant update on table "public"."prompts" to "anon";

grant delete on table "public"."prompts" to "authenticated";

grant insert on table "public"."prompts" to "authenticated";

grant references on table "public"."prompts" to "authenticated";

grant select on table "public"."prompts" to "authenticated";

grant trigger on table "public"."prompts" to "authenticated";

grant truncate on table "public"."prompts" to "authenticated";

grant update on table "public"."prompts" to "authenticated";

grant delete on table "public"."prompts" to "postgres";

grant insert on table "public"."prompts" to "postgres";

grant references on table "public"."prompts" to "postgres";

grant select on table "public"."prompts" to "postgres";

grant trigger on table "public"."prompts" to "postgres";

grant truncate on table "public"."prompts" to "postgres";

grant update on table "public"."prompts" to "postgres";

grant delete on table "public"."prompts" to "service_role";

grant insert on table "public"."prompts" to "service_role";

grant references on table "public"."prompts" to "service_role";

grant select on table "public"."prompts" to "service_role";

grant trigger on table "public"."prompts" to "service_role";

grant truncate on table "public"."prompts" to "service_role";

grant update on table "public"."prompts" to "service_role";


